# Generated by Django 4.1.7 on 2023-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
