# Generated by Django 4.1.7 on 2023-03-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_user'),
        ('employee', '0004_employee_is_return'),
    ]

    operations = [
    ]
